name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  # Use a versão do .NET do projeto

      - name: SonarCloud Begin
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"GBarcellos-code_trabalho-qualidade-de-software" /o:"gbarcellos-code" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      
      - name: Build solution
        run: dotnet build --configuration Release GBarcellos-code_trabalho-qualidade-de-software.sln # Inclua o caminho correto do .sln

      - name: SonarCloud End
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

