name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'  # Altere para a versão do seu projeto .NET

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Begin
        run: dotnet tool run dotnet-sonarscanner begin /k:"GBarcellos-code_trabalho-qualidade-de-software" /o:"gbarcellos-code" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        
      - name: Build solution
        run: dotnet build --configuration /GBarcellos-code_trabalho-qualidade-de-software.sln  # Ajuste o caminho para seu arquivo .sln ou projeto .csproj

      - name: SonarCloud End
        run: dotnet tool run dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
